export const constDefault = {
    ENTITY_ERROR_STATUS: 422,
    AUTHENTICATION_ERROR_STATUS: 401,
    FORBIDDEN_ERROR_STATUS: 403,
    NOT_FOUND_ERROR_STATUS: 404,
    INTERNAL_SERVER_ERROR_STATUS: 500
};
